name: Actions 😎

on: [ push, pull_request ]

jobs:
  build:
    name: Build game jam project ✨
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # Cache
      - uses: actions/cache@v4
        with:
          path: src/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: src
      #         unityVersion: ${{ matrix.unityVersion }}
      #         targetPlatform: ${{ matrix.targetPlatform }}

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
            #
            #  Make this action run on release to upload latest to itch
            #  release:
            #    name: Release to itch
            #    runs-on: ubuntu-latest
            #    #    if: github.event.action == 'published'
            #    steps:
            #      - uses: manleydev/butler-publish-itchio-action@master
            #        name: Deploy to Itch
            #        env:
            #          BUTLER_CREDENTIALS: ${{ secrets.ITCH_API_KEY }}
            #          CHANNEL: HTML
            #          ITCH_GAME: test-proj823014786032
            #          ITCH_USER: RyanBlignaut
            #          PACKAGE: build/WebGl
               